### ISSUE TITLE
eritrean culture

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#463]
need a separate culture from ethiopia in order to simulate eritrean war of independence

**Comment by ProfBook** [comment]
Difficult. Research indicates this wasn't a culture struggle, simply one of borders. The Eritreans left because they were under the Italians and didn't want to go to the Ethiopians, just be left on their own. The closest culture is Tigrayan - the country translates to Tigray actually - but if we do so, it means any more fracturing of Ethiopia like what happened last year would be difficult to simulate as a breakaway tigray secession would join the Eritreans.
Regardless, I suppose Tigrayan works well

**Comment by ProfBook** [comment]
Sorry for late response btw - I'm on a family vacation
