### ISSUE TITLE
possibly date related ctd for italy

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#76]
ctd at end of january, seems to be date related?

**Comment by Haidenthal** [comment]
[debug.log](https://github.com/Cold-War-Project/CWP-Main/files/11128961/debug.log)
[error.log](https://github.com/Cold-War-Project/CWP-Main/files/11128962/error.log)
[game.log](https://github.com/Cold-War-Project/CWP-Main/files/11128963/game.log)
[system.log](https://github.com/Cold-War-Project/CWP-Main/files/11128964/system.log)

could always reproduce because it happened on january 28 of the year
version: current release, no other mods
GPU is rtx 3080
